main: de.greensurvivors.greenplugin.spigot.GreenPlugin
name: GreenPlugin
api-version: ${mainMCVersion}
version: ${version}
description: ${description}
author: GreensurvivorsTeam

commands:
  greenplugin:
    description: A command.